set $mod Mod4
set $term footclient
set $menu pgrep -x --quiet wofi || swaymsg exec -q "`wofi --show drun`"
set $browser firefox
set $filemanager thunar
set $editor gtk-launch code-oss
set $resize_step 30px
set $audio_step 5
set $screenshot_path "$HOME/Pictures/Screenshot $(date +'%m.%d.%y %T').png"
set $WOBSOCK $XDG_RUNTIME_DIR/wob.sock
