default_border pixel
hide_edge_borders smart
# target                 title     bg    text   indicator border
client.focused           $mauve    $base $text  $pink     $mauve
client.focused_inactive  $surface0 $base $text  $surface0 $surface0
client.unfocused         $surface0 $base $text  $surface0 $surface0
client.urgent            $peach    $base $peach $peach    $peach
client.placeholder       $overlay0 $base $text  $overlay0 $overlay0
client.background        $base

for_window [shell="xwayland"] border pixel 4

# list available fonts with fc-list : family
font pango:Inter Semibold, JetBrainsMono Nerd Font Propo 9

exec_always --no-startup-id {
    gsettings set org.gnome.desktop.interface gtk-theme catppuccin-mocha-mauve-standard+default
    gsettings set org.gnome.desktop.interface color-scheme prefer-dark
    gsettings set org.gnome.desktop.interface icon-theme Papirus-Dark
    gsettings set org.gnome.desktop.interface font-name 'Inter 9'
    gsettings set org.gnome.desktop.interface monospace-font-name 'JetBrainsMono Nerd Font Propo 9'
}
