exec firefox
exec --no-startup-id {
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
    autotiling
    dynamic-workspaces.py
    fcitx5
    foot --server
    rm -f $WOBSOCK && mkfifo $WOBSOCK && tail -f $WOBSOCK | wob
    owncloud
    swayidle -w \
        timeout 200 'brightnessctl -q --save && brightnessctl -q set 10%' \
            resume 'brightnessctl -q --restore' \
        timeout 240 '(pgrep -x swaylock >/dev/null || chayang -d 5) && swaymsg "output * dpms off"' \
            resume 'swaymsg "output * dpms on"' \
        timeout 250 'systemctl suspend' \
        before-sleep 'playerctl pause 2>/dev/null; swaylock 2>/dev/null' \
        after-resume 'blink-leds.sh; pkill -SIGUSR1 date.sh; pkill -SIGRTMIN+3 i3blocks'
}
