include colors.conf

set $bg #000000b0
bar {
    tray_output none
    font pango:Inter Semibold, JetBrainsMono Nerd Font Propo 10 #tnum=1
    position bottom
    status_command i3blocks
    separator_symbol " ॥ "
    strip_workspace_numbers yes

    colors {
        background $bg
        statusline $overlay0
        separator  $surface0
#                          border  backgr. text
        focused_workspace  $mauve  $mauve  $base
        active_workspace   $mauve  $mauve  $base
        inactive_workspace $bg     $bg     $overlay0
        urgent_workspace   $peach  $peach  $base
    }
}
