input "type:keyboard" {
    xkb_layout us
    xkb_numlock enabled
}

mouse_warping container
input "type:mouse" {
    pointer_accel 0
}

input "type:touchpad" {
    dwt disabled
    tap enabled
    natural_scroll enabled
    middle_emulation enabled
    scroll_factor 0.3
    pointer_accel 0.6
    accel_profile "flat"
}

bindgesture swipe:3:right workspace next_on_output
bindgesture swipe:3:left workspace prev_on_output
bindgesture swipe:4:right move workspace next_on_output, workspace next_on_output
bindgesture swipe:4:left move workspace prev_on_output, workspace prev_on_output
bindgesture hold:3 floating toggle
bindgesture hold:4 exec wofi --show drun
