set $laptop eDP-1
output $laptop resolution 2560x1600 position 1920,400 scale 2

bindswitch --reload --locked lid:on output $laptop disable
bindswitch --reload --locked lid:off output $laptop enable

exec --no-startup-id '/usr/local/bin/perf 0x2'
