for_window [app_id="anki" title="New"] floating enable

for_window [app_id="engrampa" title="Compress"] floating enable, inhibit_idle open
for_window [app_id="engrampa" title="Extract"] floating enable, inhibit_idle open

for_window [app_id="firefox"] inhibit_idle fullscreen
for_window [app_id="firefox" title="^Developer Tools — "] floating enable
for_window [app_id="firefox" title="About Mozilla Firefox"] floating enable
for_window [app_id="firefox" title="Extension: (Bitwarden Password Manager) - Bitwarden — Mozilla Firefox"] floating enable
for_window [app_id="firefox" title="Launch Application"] floating enable
for_window [app_id="firefox" title="Picture-in-Picture"] floating enable, sticky enable, opacity .9
for_window [app_id="firefox" title="Revert Bookmarks"] floating enable

for_window [app_id="io.missioncenter.MissionCenter"] floating enable

for_window [app_id="org.mozilla.Thunderbird"] floating enable, move position center
for_window [app_id="org.mozilla.Thunderbird" title="- Mozilla Thunderbird$"] floating disable
for_window [app_id="org.mozilla.Thunderbird" title="Authentication Required - Mozilla Thunderbird$"] floating enable, move position center

for_window [app_id="pavucontrol"] floating enable

for_window [app_id="^[tT]hunar$" title="^Rename \\\""] floating enable
for_window [app_id="^[tT]hunar$" title="Confirm to replace files"] floating enable
for_window [app_id="^[tT]hunar$" title="File Operation Progress"] floating enable, opacity .9, inhibit_idle open

for_window [app_id="transmission-gtk" title="Torrent Options"] floating enable

for_window [app_id="wineboot.exe"] floating enable
for_window [app_id=".*\.exe$"] inhibit_idle fullscreen

for_window [urgent=latest] focus
